### ISSUE TITLE
Not working with wasm

### ISSUE THREAD

**Issue by ziyak97** [nagisa/rust_libloading#119]
Hey I am trying to build my code using wasm-unknown-unknown. wasm-pack build -t web

I get the following error when doing so

```
libloading::Library::new(full_path).expect("Could not load the jvm dynamic library")
   |                         ^^^^^^^ could not find `Library` in `libloading`
```

Would this mean the libloading::Library is not compatible with web browsers?

**Comment by nagisa** [comment]
Correct – you cannot use `libloading` with `wasm` as `wasm` does not inherently provide any mechanisms to load any other code. You will have to write a host function that does this for you and expose such loading functionality to your wasm code that way.
