### ISSUE TITLE
cant find native static library 'global_static'

### ISSUE THREAD

**Issue by echos2019** [nagisa/rust_libloading#121]
The project need libloading, but there is a problem when compile it
`error: could not find native static library `global_static`, perhaps an -L flag is missing?`
but I find the file in `target/debug/build/libloading-3703804cbed4fd2d/out/src/os/unix/global_static.o`
I wonder your help to deal with this problem
libloading used is v0.5.2

**Comment by nagisa** [comment]
Upgrade `libloading`, please. I do not have the capacity to maintain old versions of the crate, let alone those that were released 3 years ago.
