### ISSUE TITLE
Old version of dynamic library crate used unless filename/location of crate changed. 

### ISSUE THREAD

**Issue by aram0112** [nagisa/rust_libloading#132]
Hello! I've having a weird issue where when I update and compile a dynamic library crate crate to the same location, overwriting the previous crate, and try to load and run a function from that crate, it uses an outdated version of the library. However, if I copy the crate to a new location and pass in that path, the new version of the crate is used. I was wondering if this is the intended behavior or whether I'm doing something wrong or there is something else I need to do to have the latest changes reflect? Thank you so much!

**Comment by nagisa** [comment]
Probably this: https://github.com/nagisa/rust_libloading/issues/59. But either way there's nothing that libloading does specially here. The behaviour comes entirely from the how the platform you're running on is implemented, so you will have to figure out workarounds to the problem yourself.

**Comment by aram0112** [comment]
Got it, I apologize for not spotting that one earlier, thank you for your guidance!
