### ISSUE TITLE
Tests for loading variables from other libraries are missing.

### ISSUE THREAD

**Issue by tyleo** [nagisa/rust_libloading#14]
We have tests for loading functions from other libraries, but no tests for loading variables from other libraries are available. I suspect that these may not be loading correctly.

**Comment by nagisa** [comment]
I agree that testing story for this library is pretty sad. We ought to compile our own shared library and test against that instead.

**Comment by nagisa** [comment]
Fixed by https://github.com/nagisa/rust_libloading/commit/2526537f80d185a2cb02aebbe676c00813707594
