### ISSUE TITLE
Loading multiple independent instances the same library?

### ISSUE THREAD

**Issue by alshdavid** [nagisa/rust_libloading#146]
I am trying to load the same library multiple times for the purposes of a plugin. 

```rust
unsafe { libloading::Library::new(PathBuf.from("/path/to/lib.so")) }
unsafe { libloading::Library::new(PathBuf.from("/path/to/lib.so")) }
```

This seems to share state between the loaded libraries which is undesirable (the plugin uses global statics which causes conflicts when multiple instances are loaded).

I have tried to use:
```rust
let lib = unsafe {
  let lib = libloading::os::unix::Library::open(
    Some(PathBuf.from("/path/to/lib.so")),
    libloading::os::unix::RTLD_LOCAL
  ).unwrap();
  libloading::Library::from(lib)
};
```
However this give me the following error:
```
called `Result::unwrap()` on an `Err` value: 
  DlOpen { desc: "/path/to/lib.so: invalid mode for dlopen(): Invalid argument" }
```
Testing it out, if I copy the library multiple times (`lib_copy1.so`, `lob_copy2.so`, etc) - I can load that using `Library::new()` - I am just unsure how to get `libloading` to treat each instantiation as unique (I also need support for Windows).

**Comment by nagisa** [comment]
The only portable way to do this to the best of my knowledge is to have copies of the file with multiple names. If you're limited to GNU Linux, you may be able to achieve this with something like dlmopen that's been mentioned in this issue tracker in the past: https://github.com/nagisa/rust_libloading/issues/36.
