### ISSUE TITLE
Broken when cross compiling

### ISSUE THREAD

**Issue by arcnmx** [nagisa/rust_libloading#15]
`build.rs` uses `cfg` directives to determine the library to link to, which means that in a cross-compiling scenario the wrong flags (those appropriate for the host and not the build target) will be sent to the linker.

**Comment by nagisa** [comment]
Thanks for the report. I had noticed the issue this week, but was waiting until I got around to making a crate to handle target triples for build.rs… which I will do now since somebody took time to report this issue.

**Comment by nagisa** [comment]
Fix released in 0.2.3. Thanks for report.
