### ISSUE TITLE
Is it possible to catch_unwind library's panic

### ISSUE THREAD

**Issue by tkkcc** [nagisa/rust_libloading#156]
I am trying to let the host handle plugin(library)'s panic gracefully. The host can continue if one plugin panic. It works to catch_unwind at plugin side, but not at host side(cross ffi-boundary). I wonder if it is possible currently or in the future. I already use "C-unwind" abi, and rustc 1.82.0-nightly.

reproduce: https://github.com/tkkcc/libloading_catch_unwind_test

**Comment by nagisa** [comment]
You did not explain what exactly is going wrong, but in short, loading a library via libloading is no different from linking it as a shared library ahead of time. As far as I know there are no fundamental reasons why it ought to not work, but there are considerations like `C-unwind` that you appear to be using already.

Regardless, this is not a right place for user support questions – I do not have capacity for them. Consider e.g. users.rust-lang.org or other similar forums for questions on use.
