### ISSUE TITLE
dlopen for archive member

### ISSUE THREAD

**Issue by mustartt** [nagisa/rust_libloading#162]
Historically on AIX, all most of all dynamic libraries are distributed in `.a` Big Archive Format which can consists of both static and shared objects in the same archive. As a result on AIX, for `dlopen` https://www.ibm.com/docs/en/aix/7.3?topic=d-dlopen-subroutine
> RTLD_MEMBER(0x40000) - The dlopen subroutine can be used to load a module that is a member of an archive. The L_LOADMEMBER flag is used when the load subroutine is called. The module name FilePath names the archive and archive member according to the rules outlined in the load subroutine.

For example, `dlopen("libc++abi.a(libc++abi.so.1)", RTLD_MEMBER)` is used to open the dynamic library.

I want to consult before putting up an PR, as this is a plaform specific issue. Any suggestion as how to implement this?

Thank you

**Comment by nagisa** [comment]
You can use `libloading::os::unix` APIs here to open a `Library` this way and then you can convert the `Library` back to the cross-platform version through the `From/Into` traits.
