### ISSUE TITLE
thread 'main' panicked at 'could not get target info: TargetNotFound'

### ISSUE THREAD

**Issue by japaric** [nagisa/rust_libloading#19]
when cross compiling this crate for the `mips64-unknown-linux-gnuabi64`.

### Meta

Crate version: 0.3.1

```
$ rustc -V
rustc 1.14.0-nightly (098d22845 2016-10-13)
```

**Comment by nagisa** [comment]
Can you try again with the 0.1.2 version of the target_build_utils dependency?

**Comment by japaric** [comment]
@nagisa Seems to be working now. Thank you!
