### ISSUE TITLE
Unwanted `println!` debug print?

### ISSUE THREAD

**Issue by lo48576** [nagisa/rust_libloading#22]
I'm using `glutin` crate, and it depends indirectly on `libloading`.
`cargo update` updates `libloading-0.3.2` to `0.3.3`, and then 47 lines of "8" is printed to stdout...

![screenshot-2017-03-25-154855 0900](https://cloud.githubusercontent.com/assets/1246590/24320148/d19e5e10-1172-11e7-8ee7-00b66a1cec59.png)

The problem doesn't happen on `libloading-0.3.2` and I think [this change might be the cause](https://github.com/nagisa/rust_libloading/commit/7c2f4b98c44a88ee1c37f6acb671e3f22da9e318#diff-d25ef168d08ddcfeaca8453639097a59R59).

Is this `println!` necessary?
I'm happy if this println would be removed, or moved inside of the following `if` block (with more verbose message and `stderr` destination).

**Comment by nagisa** [comment]
Oh my bad! Sorry!

Released 0.3.4 with the printing removed.
