### ISSUE TITLE
Integration with rust-bindgen

### ISSUE THREAD

**Issue by baloo** [nagisa/rust_libloading#28]
I'm trying to integrate with a rust-bindgen lib defined types.

Basically, extracting types from a `.h` file and generating rust types.

My types are generated like:
```
pub type CK_C_Initialize =
    ::std::option::Option<unsafe extern "C" fn(init_args:
                                                   *mut ::std::os::raw::c_void)
                              -> ::std::os::raw::c_ulong>;
```
Which is nice but really unpractical to use with `libloading` because writing:
```
let initialize: Symbol<pkcs11_sys::CK_C_Initialize> = unsafe {
  try!(self.lib.get(b"C_Initialize"))
};
initialize();
```
does not really work because:
```
error: expected function, found `libloading::Symbol<'_, std::option::Option<unsafe extern "C" fn(*mut std::os::raw::c_void) -> u64>>`
  --> src/lib.rs:42:5
   |
42 |     initialize();
   |     ^^^^^^^^^^^^
   |
```
 I'm not sure how to extract the `Symbol<Option<T>>` to get a more useful type (something like `Option<Symbol<T>>` at very least).
I'm looking for suggestions or things I'm missing. I'd be happy to provide a pull request for this, feel free to give directions :).

**Comment by nagisa** [comment]
I missed this issue before, hence delay in answer. It is possible to add a function that does `Symbol<Option<T>>` to `Option<Symbol<T>>` conversion fairly easily, although I don’t see much point in it, when doing something along the lines of `initialize.as_ref().unwrap()` would give you a plain function pointer anyway.

**Comment by baloo** [comment]
Thank you very much for the fix and the release.
