### ISSUE TITLE
Windows synchronization bugs

### ISSUE THREAD

**Issue by szymonwieloch** [nagisa/rust_libloading#31]
Hi!

I was writting my own library for loading dynamic link libraries and while analyzing your Windows code:
https://github.com/nagisa/rust_libloading/blob/master/src/os/windows/mod.rs
I think I found two bugs:

1. Invalid behavior if SetThreadErrorMode() returns an error that is different from ERROR_CALL_NOT_IMPLEMENTED
    
    Your code basicly returns a guard with a random previous value in this case.

2. Synchronization issue when several threads call SetErrorMode().

    Please notice that when several threads call SetErrorMode() at the same time, only the first one should actually call this function to set the "1" error mode and only the last should revert the previous value. Otherwise it may happen that thread 1 obtains current error mode, then thread 2 obtains error mode (in this case always 1), then thread 1 sets error mode to its original value, then thread 2 sets error mode to what it thinks was its previous value (but it's 1 actually).

I think I have fixed those bugs in my libary, you may want to check it:

https://github.com/szymonwieloch/rust-dlopen/blob/master/src/raw/windows.rs

**Comment by nagisa** [comment]
Hi,

Thanks for the heads up.

I acknowledge the first issue, however I don't see how the 2nd one could
ever be fixed[1] -- and it not being thread safe was intended. While a
multithreaded use of this library specifically would become safe with some
use of mutexes, it is still chiefly thread unsafe overall, because anybody
can call SetErrorMode at any time without any synchronisation outside the
library.

I should mention this in the documentation.

[1]: other than upgrading to a recent windows release.

S.

**Comment by szymonwieloch** [comment]
Hi!

I agree that there is no perfect way of handling problems with SetErrorMode. The old Windows API is just poorly designed. At the same time I think that you can do better than now. As you mentioned a static mutex + counter + previous error mode value can save your application from having thread synchronization issues assuming that your library is the only one that manipulates the error mode.
At the same time it does not prevent from synchronization issues if other crates modify the error mode.

I see two solutions here:

1. Just use static mutex + counter + previous error mode value. Typical use case is that the error mode gets set once at the initialization of application and then is not modified. Your crate will be usually the only one changing it. This solution prevents thread synchronization issues on Windows in the most common case. My crate follows this approach.

2. Create a separate crate that would allow multiple crates to synchronize on setting error mode. The point here is to have one global mutex for all crates. All crates that use this synchronization crate would would synchronize and work correctly with each other. This at least crates the "right" rusty approach for working with Windows API and if you don't use is - it is fault of the user, not of Rust framework.

**Comment by nagisa** [comment]
I fixed the error handling and did some additional things (including extra documentation) to improve handling of race-conditions with `SetErrorMode`.

Thanks for the report/review.
