### ISSUE TITLE
Loaded functions cannot be marked unsafe

### ISSUE THREAD

**Issue by vberger** [nagisa/rust_libloading#4]
Using this example:

```rust
extern crate libloading;

use libloading::{Library, Symbol};

fn main() {
    let lib = Library::new("libm.so.6").unwrap();
    let sin: Symbol<unsafe extern fn(f64) -> f64> = unsafe {
        lib.get(b"sin\0").unwrap()
    };

    let _a = unsafe { sin(4.5) };
}
```
I get this compilation output
```
src/main.rs:9:14: 9:33 warning: unnecessary `unsafe` block, #[warn(unused_unsafe)] on by default
src/main.rs:9     let _a = unsafe { sin(4.5) };
                           ^~~~~~~~~~~~~~~~~~~
```

But, I loaded a symbol `unsafe extern fn(_)`, so I would expect using it to require an unsafe block.

(This example is trivial, but some FFI functions involving `void*` and varargs are totally unsafe and should be marked as such...)

**Comment by nagisa** [comment]
Umm… your code does not compile without the `unsafe` block in `let _a = unsafe { sin(4.5) };` on nightly here. What version of `rustc` are you using?

**Comment by vberger** [comment]
Oh yeah, my bad, reported too fast. It get the warning on stable but not on nightly.

I guess something was fixed in between.
