### ISSUE TITLE
Add generic export of os symbols

### ISSUE THREAD

**Issue by jnqnfe** [nagisa/rust_libloading#40]
I'm using libloading in a work-in-progress large project; there's a part of the project's design which necessitates returning a raw os symbol. Unfortunately your library currently forces me to write the following:

```
#[cfg(not(windows))]
use libloading::os::unix::Symbol as LibSymbol;
#[cfg(windows)]
use libloading::os::windows::Symbol as LibSymbol;
```

Which is messier than I'd like. Could you please add a generic export of os symbols (i.e. ::os::raw::*) to provide a cleaner import of the os symbols, just like std does. Thanks :)

**Comment by nagisa** [comment]
The current scheme actually mimics the libstd behaviour fairly closely and in your code example achieves the intended purpose – to make platform specific dependencies very visible – fairly well.

A better example from libstd similar to the `Symbol` case would be [`RawFd`](https://doc.rust-lang.org/stable/std/os/unix/io/type.RawFd.html) vs [`RawHandle`](https://doc.rust-lang.org/stable/std/os/windows/io/type.RawHandle.html).

**Comment by nagisa** [comment]
I'm going to close this out as I believe re-exporting the OS-specific API at a common path would be a mistake at this time. If we ever end up getting an implementation of something like the [portability lint](https://rust-lang.github.io/rfcs/1868-portability-lint.html) the approach on how the APIs are designed would change, but the change would affect significantly more than just this API.
