### ISSUE TITLE
List available symbols, functions

### ISSUE THREAD

**Issue by mcandre** [nagisa/rust_libloading#48]
Could libloading provide a way to query a library to get the list of available symbols and functions? I’m working on a basic mage port to Rust, and it would help if I could reflect over library entries rather than hardcode them.

As a workaround, I’m thinking of having my libraries adhere to a specific Rust trait, which would itself offer methods for registering and querying symbols and functions. But it would be cooler to do this dynamically rather than impose a structure on the plugins I use.

**Comment by nagisa** [comment]
There are no system-provided utilities to do so on Unix or Windows AFAICT.

On UNIX obtaining the symbol table would involve parsing ELF, which is way out of scope for this library IMHO, and on windows it may involve linking in some debug-oriented system library which may be undesirable to do by default.

**Comment by nagisa** [comment]
That being said, if I got a PR with a cross-platform implementation of this behind a feature flag, I’d gladly merge it.

**Comment by nagisa** [comment]
I’m going to close this out as one of the many crates for parsing executable files can serve this use-case instead. Some of the crates that can help with this are [object](https://crates.io/crates/object) and [goblin](https://crates.io/crates/goblin).
