### ISSUE TITLE
Include example that shows how to wrap library in struct

### ISSUE THREAD

**Issue by hbgl** [nagisa/rust_libloading#50]
Hello.
First of all, thanks for this great library. I am pretty new to Rust and I need to call a few functions inside a Windows DLL from Rust. To keep things clean I want to stick the symbols into a struct and provide a safe interface. But I cannot figure out how to do this. So I thought it would be nice if the documentation had an example on how to provide a safe wrapper.

**Comment by nagisa** [comment]
Hi, there are crates which depend on libloading which provide exactly that in a convenient package: [sharedlib](https://github.com/Tyleo/sharedlib) for example.

If you want to use libloading specifically, you will have to use the `libloading::os` interface which does not tie lifetime of the symbols to library they come from, or use a crate like [rental](https://crates.io/crates/rental).

**Comment by nagisa** [comment]
For what it is worth, I had a desire to improve and provide multiple different interfaces in the past. This could be one of those interfaces.

**Comment by nagisa** [comment]
Err, I’m sorry I meant to link [shared_library](https://docs.rs/shared_library/0.1.9/shared_library/), not `sharedlib`.

**Comment by hbgl** [comment]
Thanks, this is very good information. I will take a look at it.
