### ISSUE TITLE
Get inner handle

### ISSUE THREAD

**Issue by Tarnadas** [nagisa/rust_libloading#52]
I was trying to use this library to build a frontend for Mupen64Plus.
However the [Plugin API](http://www.mupen64plus.org/wiki/index.php?title=Mupen64Plus_v2.0_Plugin_API) requires a void pointer to the core library.

The first thing I tried is giving it the pointer to the Library struct instead of the handle but it is doing some weird things. ~It seems like it can call the functions from the Core lib handle, but it can't do it properly, resulting in error return messages.~ Giving it a null pointer results in the same error message, so it cannot call the functions from the Library.

So I was modifying this library to expose the inner handle, so that I can pass it properly to Mupen64Plus and now it works. Is there any other way to get the inner handle?
Would you like me to send a PR for this?

**Comment by nagisa** [comment]
If you end up needing to use the raw primitives, you’re probably better off using the C API to do the loading in the first place, but I would not object to adding conversion methods to convert from the OS-specific `Library` to its inner handle and vice versa.
