### ISSUE TITLE
Get the dll and function for SetWindowsHookExA

### ISSUE THREAD

**Issue by Adarma** [nagisa/rust_libloading#56]
How do I get a `HINSTANCE` from the `Library`, and `HOOKPROC` from the `Symbol`?

I want to use them in a `SetWindowsHookExA` call.

```
HHOOK SetWindowsHookExA(
  int       idHook,
  HOOKPROC  lpfn,
  HINSTANCE hmod,
  DWORD     dwThreadId
);
```

**Comment by nagisa** [comment]
`Library` is a `HMODULE`, not `HINSTANCE` and `Symbol` is a `FARPROC`, not `HOOKPROC`; and currently neither provides a way to obtain the underlying OS resource, so your best bet is to use `winapi` APIs directly.
