### ISSUE TITLE
[Question] How `libloading` find the DLL file when just giving a name?

### ISSUE THREAD

**Issue by tan-wei** [nagisa/rust_libloading#58]
When I use [genet](https://github.com/genet-app/genet), it complains that `wpcap.dll` can not be found so `Winpcap` should be installed. But in my computer, `Npcap` is installed instead of `Winpcap`, however, they can not coexist. So I try to copy the required DLLs (`wpcap.dll`, usually `Packet.dll` should also be included) in the installation directory of `genet`.

However, it still complains "wpcap.dll is not found". After I dig into the source code, I find that `genet` use `libloading` to load the DLL in Windows just like this:
```rust
let lib = libloading::Library::new("Wpcap.dll").map_err(|_| super::Error::DLLNotFound)?;
```
I have a question here, how `libloading` find the DLL file when just given a name? What sequence? Thanks!

**Comment by nagisa** [comment]
libloading searches in the same locations, and in the same order, as native platform APIs. For Windows specifically see [this MSDN article](https://docs.microsoft.com/en-gb/windows/win32/dlls/dynamic-link-library-search-order).

**Comment by tan-wei** [comment]
Thanks for rapid reply.
