### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by lilianmoraru** [nagisa/rust_libloading#6]
Under unix you have code that handles most platforms but no Android. Note that Android uses bionic instead of glibc.
"ios" is also a platform that should probably have the same code as any unix implementation.
Is this support planned?

**Comment by nagisa** [comment]
I wonder if it doesn’t work already. If it doesn’t, that’s a bug and will eventually get fixed.

**Comment by lilianmoraru** [comment]
Yes, it should work as is.

**Comment by nagisa** [comment]
I tweaked `cfg`s to be more inclusive in https://github.com/nagisa/rust_libloading/commit/2a04b62a618add685e7ad4af7cf201ff58f74ae5. Please test.
