### ISSUE TITLE
Allow altering search path - add LoadLibraryExW on Windows

### ISSUE THREAD

**Issue by NightRa** [nagisa/rust_libloading#65]
We've got a scenario where we want to alter the search path of LoadLibrary, which is done via the flags passed to [LoadLibraryExW](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw).

For example, we would like to avoid searching the user's PATH for the library, and only search the application directory - which is the flag [LOAD_LIBRARY_SEARCH_APPLICATION_DIR](https://docs.rs/winapi/latest/winapi/um/libloaderapi/index.html).

So this means adding another `new` function to the windows-specific module, which calls `LoadLibraryExW`, and allows passing flags. (Note they may be combined, so we can use the [bitflags](https://docs.rs/bitflags/1.2.1/bitflags/) crate for that)

Relevant issues:
https://github.com/rust-windowing/glutin/issues/1292
https://github.com/feenkcom/gtoolkit/issues/973

**Comment by nagisa** [comment]
Do you want to submit a pull request with the proposed constructor? Unix [already has a similar function](https://docs.rs/libloading/0.6.0/libloading/os/unix/struct.Library.html#method.open) that accepts platform-specific flags, so I don’t see much reason to not add a similar one for Windows.
