### ISSUE TITLE
Error: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by jackcmay** [nagisa/rust_libloading#67]
I'm seeing the following error on Linux only when loading a dynamic object:

`cannot allocate memory in static TLS block`

Is there a workaround within the Rust environment for this?  Any guidance?  Thanks!

**Comment by nagisa** [comment]
The issue I believe is within the library being loaded, not the environment that’s loading the library. The relevant issues all appear to be related with the use of non-system allocators. See for instance https://github.com/jemalloc/jemalloc/issues/937.

**Comment by jackcmay** [comment]
Thanks, agreed

FYI:
Adding the following to the shared object's Cargo.toml:
`jemalloc-sys = { version = "0.3.2", features = ["disable_initial_exec_tls"] }`

That feature is described here:
https://crates.io/crates/jemalloc-sys
