### ISSUE TITLE
Add illumos to link_libraries

### ISSUE THREAD

**Issue by papertigers** [nagisa/rust_libloading#68]
Can we add `"illumos" => {}"` to `fn link_libraries()` so that the new illumos triple is recognized as a known target? I can open a PR if you would like.

**Comment by nagisa** [comment]
Yes we can. Feel free to open a PR.

**Comment by nagisa** [comment]
Fixed by 8522c3f, will publish a release momentarily.

**Comment by papertigers** [comment]
Thanks for grabbing this.  Sorry I didn't get a chance to open the PR.
