### ISSUE TITLE
linuxbrew ldd vs debian ldd.  Easy way to override?

### ISSUE THREAD

**Issue by silasb** [nagisa/rust_libloading#76]
Hi,

I was having issues getting `rocksdb` crate to build.  The issue that I was having was that `libloading` crate picking up the wrong shared libraries. This could be an `libc` issue as well.

The error I was getting was:

> 'Unable to find libclang: "the `libclang` shared library at /usr/lib/llvm-10/lib/libclang-10.so.1 could not be opened: libstdc++.so.6: cannot open shared object file: No such file or directory"

What was interesting was `ldd` was also returning the missing libraries.  This is what I was getting with the linuxbrew `ldd`

```
ldd /usr/lib/llvm-10/lib/libclang-10.so.1
ldd: warning: you do not have execution permission for `/usr/lib/llvm-10/lib/libclang-10.so.1'
/usr/lib/llvm-10/lib/libclang-10.so.1: /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libm.so.6: version `GLIBC_2.27' not found (required by /usr/lib/llvm-10/lib/../lib/libLLVM-10.so.1)
	linux-vdso.so.1 (0x00007ffde8db7000)
	libdl.so.2 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libdl.so.2 (0x00007f188569c000)
	libLLVM-10.so.1 => /usr/lib/llvm-10/lib/../lib/libLLVM-10.so.1 (0x00007f1880b17000)
	libpthread.so.0 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libpthread.so.0 (0x00007f18808fa000)
	libstdc++.so.6 => not found
	libm.so.6 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libm.so.6 (0x00007f18805f4000)
	libgcc_s.so.1 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libgcc_s.so.1 (0x00007f18803dd000)
	libc.so.6 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/libc.so.6 (0x00007f188003d000)
	/home/silas/.linuxbrew/Cellar/glibc/2.23/lib64/ld-linux-x86-64.so.2 (0x00007f188788d000)
	libffi.so.6 => not found
	libedit.so.2 => not found
	libz.so.1 => not found
	librt.so.1 => /home/silas/.linuxbrew/Cellar/glibc/2.23/lib/librt.so.1 (0x00007f187fe35000)
	libtinfo.so.6 => not found
	libstdc++.so.6 => not found
```

This is what I got with Debian `ldd`

```
/usr/bin/ldd /usr/lib/llvm-10/lib/libclang-10.so.1
	linux-vdso.so.1 (0x00007ffe9cbf4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f08138d0000)
	libLLVM-10.so.1 => /usr/lib/llvm-10/lib/../lib/libLLVM-10.so.1 (0x00007f080ed4b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f080ed2a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f080eba6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f080ea23000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f080ea09000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f080e846000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f08158d2000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f080e83c000)
	libedit.so.2 => /usr/lib/x86_64-linux-gnu/libedit.so.2 (0x00007f080e805000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f080e5e7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f080e5dd000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f080e5af000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f080e593000)
```

The only way that I could fix this was to remove `$HOME/.linuxbrew/bin` from my PATH and then call `cargo build`.  This is annoying and tricky to debug, but it worked.  Is there a better way to solve this other than changing my PATH, maybe by forcing `libloading` or maybe `libc` crate to use an `ldd` that I specify?

**Comment by nagisa** [comment]
`libloading` does not use and does not care about the `ldd`. The only thing that matters (on Linux) is the `ld-linux-*.so` loader as it implements the loading of the dynamic libraries. It searches for libraries in accordance to various environment variables (`LD_LIBRARY_PATH`), various metadata found within the library being loaded (`DT_RPATH`, `DT_RUNPATH`) and system wide config (`ld.so.cache` found in a location relative to `ld-linux-*.so`). On a typical debian installation `ld.so.cache` is the primary and usually the only mechanism used.

Given that you appear to be using `linuxbrew`'s `ld-linux`, that can only mean that the linuxbrew sysroot is either:

* Missing prerequisite libraries (not installed);
* Linuxbrew project didn’t correctly set the various metadata in the libraries it installed;
* Linuxbrew failed to correctly set-up the `ld.so.cache`.

**Comment by silasb** [comment]
From what I can tell, the host LLVM is getting confused because of `linuxbrew`'s `ld.so` that is inside my `PATH`  over my host system `ld.so`.

I doubt that I can make the libraries from `linuxbrew` happy with my host LLVM. Especially since I have  `glibc` installed from `linuxbrew`. I'll continue altering my `PATH` to specify my host system `ld.so` over `linuxbrew`'s when hacking away.

Thanks for the info.
