### ISSUE TITLE
SetThreadErrorMode not found in WindowsXP

### ISSUE THREAD

**Issue by DominicD** [nagisa/rust_libloading#80]
I tried to run my rust binary on WindowsXP however when I use libloading I get an Error which says "SetThreadErrorMode" not found in "Kernel32.dll". In the docs I read the following: 

> Thread-safety
The implementation strives to be as MT-safe as sanely possible, however due to certain error-handling related resources not always being safe, this library is not MT-safe either.
On Windows Vista and earlier error handling falls back to SetErrorMode, which is not MT-safe. MT-scenarios involving this function may cause a traditional data race;

So I was hoping that SetErrorMode is used which is available on WindowsXP as far as I know.
Is there something I can do to make it work? 

If you need more info just tell me 
Thanks!

**Comment by nagisa** [comment]
I don't have access to either Windows version so you will need to submit a PR to fix how libloading uses `SetThreadErrorMode`. It currently checks whether Windows [reports the call being unimplemented](https://github.com/nagisa/rust_libloading/blob/4ad1af8ae9d577562e5dc1280f222713a17e8cf2/src/os/windows/mod.rs#L325) and then falls back. In retrospective this is linking to the symbol statically, so there needs to be something else (weak linking?) as well.

**Comment by DominicD** [comment]
Thank you for the fast answer. 
To be honest I don't have enough knowledge to be able to do something about this myself. 
E.g. I don't know what weak linking is.

**Comment by nagisa** [comment]
Following the drop of support for Windows XP by the [rust project](https://github.com/rust-lang/compiler-team/issues/378) we will be doing the same.

I'm happy to accept a PR that adds the support back in a non-broken state, however. But given that `libstd` itself is no longer supporting XP, that will probably end up being quite infeasible!
