### ISSUE TITLE
How to use libloading with actix-web, please

### ISSUE THREAD

**Issue by d892fc** [nagisa/rust_libloading#81]
How to use libloading to load the following 3 functions?

```
use actix_web::{get, post, web, App, HttpResponse, HttpServer, Responder};

#[get("/")]
async fn hello() -> impl Responder {
    HttpResponse::Ok().body("Hello world!")
}

#[post("/echo")]
async fn echo(req_body: String) -> impl Responder {
    HttpResponse::Ok().body(req_body)
}

async fn manual_hello() -> impl Responder {
    HttpResponse::Ok().body("Hey there!")
}
```

**Comment by nagisa** [comment]
Thanks for your interest in using `libloading`!

You can't trivially do what you described, at least not directly. You will have to write a FFI wrapper around the server, possibly in its entirety if you want to make it dynamically loadable to any meaningful degree. How to do so is not exactly a `libloading` question, but a more general Rust one. I can recommend stackoverflow or [users.rust-lang.org](https://users.rust-lang.org/) for these kinds of questions.
