### ISSUE TITLE
Undefined behavior in `fmt::Debug` impl for `os::windows::Library`

### ISSUE THREAD

**Issue by Cldfire** [nagisa/rust_libloading#83]
I happened to notice this while glancing around the code for #82. [Link to src](https://github.com/nagisa/rust_libloading/blob/master/src/os/windows/mod.rs#L241-L242).

```rust
            let mut buf =
                mem::MaybeUninit::<[mem::MaybeUninit::<WCHAR>; 1024]>::uninit().assume_init();
```

Based on [the docs for `assume_init`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html#method.assume_init), it sounds like this is UB:

> Calling this when the content is not yet fully initialized causes immediate undefined behavior.

**Comment by Cldfire** [comment]
Oh, duh. That's not UB because the contents of the array *are* actually initialized there, as uninitialized data.

Also realized it's [copied from the impl in the stdlib](https://doc.rust-lang.org/stable/src/core/mem/maybe_uninit.rs.html#304-307).

Closing, my bad! 😄

**Comment by nagisa** [comment]
The `assume_init` is fine becaue the array values are themselves `MaybeUninit`, yeah.
