### ISSUE TITLE
about parameter and return value

### ISSUE THREAD

**Issue by huanghu578** [nagisa/rust_libloading#88]
fn call_dynamic() -> Result<u32, Box<dyn std::error::Error>> {
    unsafe {
        let lib = libloading::Library::new("/path/to/liblibrary.so")?;
        let func: libloading::Symbol<unsafe extern fn() -> u32> = lib.get(b"my_func")?;
        Ok(func())
    }
}

How can I pass parameters into func ,and get a return value?

**Comment by nagisa** [comment]
Please consult the documentation. There are examples such as [this one](https://docs.rs/libloading/0.7.0/libloading/struct.Library.html#examples-1) which exemplify loading and calling of parametrised functions.
