### ISSUE TITLE
How to access Library as a static variable?

### ISSUE THREAD

**Issue by buzmeg** [nagisa/rust_libloading#90]
I've been trying to set up my Library at the beginning of my program from the main thread which will then get accessed by other threads to load up local function pointers from the library.

However, I'm having a murderously difficult time pulling this off.  I'm basically bumping into all kinds of "move occurs because `x` has type `libloading::Library`, which does not implement the `Copy` trait".  I'm not surprised.  I'm certainly fighting the "Rust Way(tm)" here.  Although, I'm a little surprised as those are just Handles/Function Pointers at bottom, no?

My first question is: If I want that Library to be at static scope so multiple threads can use it, how do I pull that off?

My second question is: Am I going to run into similar problems with Symbol if I have a couple of them at global static scope (ie. the primary loader functions)?

Thanks.

**Comment by nagisa** [comment]
> those are just Handles/Function Pointers at bottom

That is correct. However `Library` is not `Copy` nor `Clone` for the same reasons `File` is not – it represents a resource and cloning would require duplicating a handle in a way that would inform the underlying system of the duplication. To implement such a duplication support it would be required that `Library` holds not just the handle to the library, but also a lot of other data necessary to construct a new such handle.

> If I want that Library to be at static scope so multiple threads can use it, how do I pull that off?

`lazy_static!` is something many had a fair success with. Something from the [`std::lazy`](https://doc.rust-lang.org/stable/std/lazy/index.html) module could also be useful if you're comfortable with using unstable functionality.

> Am I going to run into similar problems with Symbol if I have a couple of them at global static scope (ie. the primary loader functions)?

Not necessarily, but I don't know the specifics of how your code is constructed to tell for sure.

**Comment by buzmeg** [comment]
It's a bit strange.  Library by itself goes through lazy_static! just fine, but compositions of containing things sometimes don't.  Weird.

Not a bug in libloading.  Closing.
