### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by Ericson2314** [nagisa/rust_libloading#92]
https://github.com/nagisa/rust_libloading/blob/7fbd3a34336f7839bdd6d6aaf83a9a763c4fa1e5/src/os/unix/mod.rs#L245

I am getting
```
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
   --> src/os/unix/mod.rs:245:9
    |
245 |         extern crate cfg_if;
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #27812 <https://github.com/rust-lang/rust/issues/27812> for more information
```
with a build using https://github.com/kolloch/crate2nix

**Comment by nagisa** [comment]
The `cfg-if` dependency is specified [here](https://github.com/nagisa/rust_libloading/blob/9376540678fe0670ee9e9f5cd3b2b66d94389e8e/Cargo.toml#L23). I suspect this may be a bug in `crate2nix` around this form of dependency specification. Wouldn't be [the first time](https://github.com/kolloch/crate2nix/issues/141).

**Comment by Ericson2314** [comment]
@nagisa Gahh. I tried to find the dep here, and an existing issue on the crate2nix side, and failed on both counts. Thank you!
