### ISSUE TITLE
Consider adding libloading::Library::this()

### ISSUE THREAD

**Issue by MatrixDev** [nagisa/rust_libloading#96]
Currently Library struct has only one method for creation - `Library::new()`. It would be really nice to add `Library::this()` as well. It is already implemented for unix and windows anyways.

So instead of writing this:
```rust
#[cfg(unix)]
fn open_self(..) -> Result<Library> {
    Ok(Library::from(libloading::os::unix::Library::this()))
}
#[cfg(windows)]
fn open_self(..) -> Result<Library> {
    Ok(Library::from(libloading::os::windows::Library::this()?))
}

let library = open_self();
```

Users can just simply write:
```rust
let library = Library::this();
```

Yes, `libloading::os::unix::Library::this()` cannot fail. But it doesn't really matter when you're writing cross-platform code, as you need to handle errors from everywhere anyways. This can be considered as a very useful helper.

**Comment by nagisa** [comment]
The behaviour between the two environments is sufficiently distinct in what symbols are made available that a common cross-platform wrapper isn't really feasible.

**Comment by MatrixDev** [comment]
Thanks for a quick reply. You can close this issue if there are really no common symbols that can be accessed.

**Comment by nagisa** [comment]
Thank you for taking time to request a change regardless.
